version: 2

updates:
  # تحديث Gradle ecosystem بالكامل
  - package-ecosystem: "gradle"
    directory: "/"

    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Europe/Amsterdam"

    open-pull-requests-limit: 1

    labels:
      - "dependencies"
      - "android"
      - "gradle"
      - "wrapper"

    commit-message:
      prefix: "deps"
      include: "scope"

    rebase-strategy: "auto"

    groups:
      all-gradle-updates:
        patterns:
          - "*"

    reviewers:
      - "code-with-maher"

  # تحديث GitHub Actions والـ runner actions
  - package-ecosystem: "github-actions"
    directory: "/"

    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:10"
      timezone: "Europe/Amsterdam"

    open-pull-requests-limit: 1

    labels:
      - "ci"
      - "github-actions"

    commit-message:
      prefix: "ci"

    groups:
      all-actions-updates:
        patterns:
          - "*"

    reviewers:
      - "code-with-maher"