# تحسين أداء الذاكرة أثناء البناء
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError

# تفعيل الأندرويد إكس (إجباري حالياً)
android.useAndroidX=true

# تعطيل الجيتيفاير لتسريع البناء (إلا إذا كنت تستخدم مكتبات من العصر الحجري)
android.enableJetifier=false

# القنبلة الذرية لتقليل الحجم: تفعيل الوضع الكامل للـ R8
# هذا سيجعل الـ 5.9 ميجا تنهار لأسفل، لكنه يتطلب قواعد برو جارد دقيقة
android.enableR8.fullMode=true

# تحسينات إضافية للسرعة
org.gradle.parallel=true
org.gradle.caching=true
android.nonTransitiveRClass=true
