org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon=true
org.gradle.vfs.watch=true

android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.control.runInSeparateProcess=true

kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
kotlin.code.style=official
