name: Generate Maher Keystore

on:
  workflow_dispatch:
    inputs:
      store_password:
        description: 'Keystore Password'
        required: true
      key_password:
        description: 'Key Password'
        required: true
      alias_name:
        description: 'Key Alias'
        required: true
        default: 'maher_key'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkey -v \
            -keystore maher_release.jks \
            -alias ${{ github.event.inputs.alias_name }} \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass ${{ github.event.inputs.store_password }} \
            -keypass ${{ github.event.inputs.key_password }} \
            -dname "CN=maher, OU=maher, O=maher, L=aleppo, ST=aleppo, C=sy"

      - name: Output Base64
        run: |
          echo "---------------- COPY START ----------------"
          base64 -w 0 maher_release.jks
          echo -e "\n---------------- COPY END ----------------"

      - name: Upload Keystore Artifact
        uses: actions/upload-artifact@v4
        with:
          name: maher-keystore-file
          path: maher_release.jks