name: Create Labels Manually

on:
  workflow_dispatch:

jobs:
  create-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create labels
        uses: actions-ecosystem/action-create-labels@v1
        with:
          labels: |
            android
            dependencies
            gradle
            wrapper
            ci
            github-actions